version: "3.9"

services:
  python-service:
    build:
      context: .  # Set context to the root directory
      dockerfile: /Dockerfile  # Specify the Dockerfile path
    ports:
      - "8000:8000"
    volumes:
      - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: