version: "3.9"
services:
  python-service:
    image: tristanberkie/eindopdracht_api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    volumes:
      - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: