name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Update to the latest version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .  # Set context to the root directory
        file: docker/Dockerfile  # Path to Dockerfile relative to the context
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/jobtrack:latest

    - name: Verify Docker Image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/jobtrack:latest
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/jobtrack:latest uvicorn --host 0.0.0.0 --port 8000 --app-dir /code app.main:app