name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .  # Build context is the root directory
        file: Dockerfile  # Path to Dockerfile relative to the build context
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/jobtrack:latest

    - name: Verify Docker Image
      run: |

        docker pull ${{ secrets.DOCKER_USERNAME }}/jobtrack:latest
        
        # Run the Docker container in detached mode
        docker run -d --name jobtrack_test -p 8000:80 ${{ secrets.DOCKER_USERNAME }}/jobtrack:latest
        
        # Wait for a few seconds to let the server start
        sleep 10

        # Test if the application is responding
        curl --silent --fail http://localhost:8000 || (docker logs jobtrack_test && exit 1)

        # Clean up
        docker stop jobtrack_test
        docker rm jobtrack_test